[phases.setup]
nixPkgs = ["nodejs_20", "python3", "litestream"]

[phases.install]
cmds = [
  "cd server && npm install --include=dev",
  "cd client && npm install --include=dev"
]

[phases.build]
cmds = [
  "cd server && npm run build",
  "cd client && npm run build",
  "chmod +x /app/start.sh"
]

[start]
cmd = "/app/start.sh"
